firstName = input("What is your first name")
firstName = input()
lastName = input("What is your last name")
lastName = input()
age = input("What is your age")
age = int(input())
town = input("What is your hometown")
town = input()
print(f"You are {firstName} {lastName}, a {age}-years old person from {town}.")